# Generated by Django 5.1.1 on 2024-10-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/defaults/default_profile.png', upload_to='users/profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
