# Generated by Django 5.1.1 on 2024-11-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cart',
            new_name='cart_cart_user_id_b645f9_idx',
            old_name='cart_cart_user_id_e6a21d_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='cart_cartit_cart_id_4bd8c3_idx',
            old_name='cart_cartit_cart_id_51147f_idx',
        ),
    ]
