name: Django CI
run-name: ${{ github.actor }} is running Django CI
on:
 push:
   branches:
     - '*'
 pull_request:
   branches: [ dev, backup ]
 workflow_dispatch:

jobs:
 Django-Lint:
   runs-on: ubuntu-latest
   steps:
     - name: Debug GitHub context
       run: |
         echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
         echo "GITHUB_REF: $GITHUB_REF"
         echo "GITHUB_SHA: $GITHUB_SHA"
         echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"

     - name: Check out repository code
       uses: actions/checkout@v4

     - name: Debug directory
       run: |
         echo "Current directory: $(pwd)"
         echo "Directory structure:"
         tree || ls -R
         echo "Files in current directory:"
         ls -la

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'

     - name: Install Dependencies
       working-directory: ./CSUF_BM
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         pip install flake8 black

     - name: Run Black code formatter check
       working-directory: ./CSUF_BM
       run: |
         echo "Running Black code formatting check..."
         black .

     - name: Run Flake8 Linting
       working-directory: ./CSUF_BM
       run: |
         echo "Running Flake8 linting checks..."
         # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         # Run full lint check
         flake8 . --count --exit-zero --max-complexity=10 --statistics

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

     - name: Process and Upload README to S3
       working-directory: ./CSUF_BM
       run: |
         DESCRIPTION="CSUF_Black_Market_CMS_and_WebApp"  # Using underscores instead of spaces
         echo "Copying README with new name..."
         cp README.md "README_$DESCRIPTION.md"
         echo "Uploading to S3..."
         aws s3 cp "README_$DESCRIPTION.md" s3://csuf-cpsc-362
         echo "Upload complete"

     - run: echo "CI completed with status - status WIP"
